import { Route } from "lucide-react";
import { locations } from "../../data/mockData";
import type { RouteRequest } from "../../types";

function RoutePanel({ onSubmit, loading }: { onSubmit: (request: RouteRequest) => Promise<void>; loading: boolean }) {
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); await onSubmit({ origin: String(data.get("origin")), destination: String(data.get("destination")) }); }
  return <form onSubmit={submit} className="border border-slate-200 bg-white p-5 sm:p-6"><h2 className="text-lg font-semibold text-slate-900">Where are you going?</h2><p className="mt-1 text-sm leading-6 text-slate-600">Choose your start and destination. We’ll avoid known hazards where possible.</p><div className="mt-6 space-y-5"><label className="block text-sm font-medium text-slate-700">Starting location<select required disabled={loading} name="origin" defaultValue="" className="mt-2 w-full border border-slate-300 bg-white px-3 py-3 text-base text-slate-900 outline-none disabled:bg-slate-100 focus:border-blue-700"><option value="" disabled>Select starting location</option>{locations.map((item) => <option key={item}>{item}</option>)}</select></label><label className="block text-sm font-medium text-slate-700">Destination<select required disabled={loading} name="destination" defaultValue="" className="mt-2 w-full border border-slate-300 bg-white px-3 py-3 text-base text-slate-900 outline-none disabled:bg-slate-100 focus:border-blue-700"><option value="" disabled>Select destination</option>{locations.map((item) => <option key={item}>{item}</option>)}</select></label><button disabled={loading} className="flex w-full items-center justify-center gap-2 border border-blue-700 bg-blue-700 px-4 py-3 text-sm font-medium text-white hover:bg-blue-800 disabled:cursor-not-allowed disabled:bg-blue-400">{loading ? "Finding safe route…" : <><Route size={17} />Find Safe Route</>}</button></div></form>;
}
export default RoutePanel;
