import { useState } from "react";
import { Check, ShieldCheck } from "lucide-react";

function SettingsPage() {
  const [settings, setSettings] = useState({ alerts: true, sounds: false, updates: true });
  const [saved, setSaved] = useState(false);
  const options = [{ key: "alerts", title: "Critical risk alerts", description: "Receive alerts for critical incidents." }, { key: "sounds", title: "Alert sound", description: "Play a sound when a critical report arrives." }, { key: "updates", title: "Service updates", description: "Show route and service updates." }] as const;
  return <div className="mx-auto max-w-3xl space-y-5"><section className="border-b border-slate-200 pb-5"><p className="text-sm font-medium text-slate-500">Preferences</p><h1 className="mt-1 text-2xl font-semibold text-slate-900">Settings</h1><p className="mt-1.5 text-sm leading-6 text-slate-600">Manage notifications for this session.</p></section><section className="border border-slate-200 bg-white"><div className="border-b border-slate-200 p-5"><div className="flex items-center gap-3"><div className="p-2 text-blue-700"><ShieldCheck size={20} /></div><div><h2 className="font-semibold text-slate-900">Notifications</h2><p className="text-sm text-slate-500">Choose which alerts appear in the app.</p></div></div></div><div className="divide-y divide-slate-200">{options.map(({ key, title, description }) => <label key={key} className="flex cursor-pointer items-center justify-between gap-5 p-5"><div><p className="text-sm font-medium text-slate-800">{title}</p><p className="mt-1 text-sm text-slate-500">{description}</p></div><input aria-label={title} type="checkbox" checked={settings[key]} onChange={() => setSettings((current) => ({ ...current, [key]: !current[key] }))} className="h-5 w-5 accent-blue-700" /></label>)}</div><div className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm text-slate-500">Preferences are stored until this page is refreshed.</p><button onClick={() => setSaved(true)} className="flex w-fit items-center gap-2 border border-blue-700 bg-blue-700 px-4 py-2.5 text-sm font-medium text-white hover:bg-blue-800">{saved && <Check size={15} />} {saved ? "Saved" : "Save changes"}</button></div></section><section className="border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-900">Service status</h2><p className="mt-2 flex items-center gap-2 text-sm text-emerald-700"><span className="h-2 w-2 rounded-full bg-emerald-600" />All services available.</p></section></div>;
}
export default SettingsPage;
