import { useState } from "react";
import { Check, ShieldCheck } from "lucide-react";

function SettingsPage() {
  const [settings, setSettings] = useState({ alerts: true, sounds: false, updates: true });
  const [saved, setSaved] = useState(false);
  const options = [{ key: "alerts", title: "Critical risk alerts", description: "Receive in-app alerts for critical incidents." }, { key: "sounds", title: "Alert sound", description: "Play a sound when a critical report arrives." }, { key: "updates", title: "Operational updates", description: "Show system and route status updates." }] as const;
  return <div className="mx-auto max-w-3xl space-y-6"><section><p className="text-[10px] font-bold uppercase tracking-[.18em] text-cyan-400">Configuration</p><h1 className="mt-2 text-2xl font-bold">System settings</h1><p className="mt-2 text-sm text-slate-400">Manage local command-center preferences for this session.</p></section><section className="rounded-xl border border-slate-800 bg-slate-900"><div className="border-b border-slate-800 p-5"><div className="flex items-center gap-3"><div className="rounded-lg bg-cyan-400/10 p-2 text-cyan-400"><ShieldCheck size={18} /></div><div><h2 className="font-semibold">Notifications</h2><p className="text-xs text-slate-500">Control alerts shown in the command center.</p></div></div></div><div className="divide-y divide-slate-800">{options.map(({ key, title, description }) => <label key={key} className="flex cursor-pointer items-center justify-between gap-5 p-5"><div><p className="text-sm font-medium">{title}</p><p className="mt-1 text-xs text-slate-500">{description}</p></div><input aria-label={title} type="checkbox" checked={settings[key]} onChange={() => setSettings((current) => ({ ...current, [key]: !current[key] }))} className="h-5 w-5 accent-cyan-400" /></label>)}</div><div className="flex items-center justify-between gap-4 p-5"><p className="text-xs text-slate-500">Preferences are stored until this page is refreshed.</p><button onClick={() => setSaved(true)} className="flex shrink-0 items-center gap-2 rounded-lg bg-cyan-400 px-4 py-2.5 text-xs font-bold text-slate-950 hover:bg-cyan-300">{saved && <Check size={15} />} {saved ? "Saved" : "Save changes"}</button></div></section><section className="rounded-xl border border-slate-800 bg-slate-900 p-5"><h2 className="font-semibold">System status</h2><p className="mt-2 flex items-center gap-2 text-sm text-emerald-300"><span className="h-2 w-2 rounded-full bg-emerald-400" />All monitored services are operational.</p></section></div>;
}
export default SettingsPage;
